name: Test files
on:
    push:
        branches:
            - master
jobs:
    main:
        runs-on: ubuntu-latest
        steps:
            -
                uses: actions/checkout@v2
            -
                name: Install dependencies
                run: sudo apt-get install jq
            -
                name: Verify python requirements
                run: sudo pip3 install -r requirements.txt
            -
                name: Test main.py
                run: |
                    python3 main.py test
            -
                name: Verify schedule.json
                run: |
                    echo "$(cat schedule.json)" | jq empty
